#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "You need to pass arguments"
    exit 0
fi

path=$1
skip=$2

dirname=`basename $path`
output_dir=data/processed/$dirname

mkdir -p $output_dir

find $path -type f \
    | xargs -I{} awk "
        \$2 > $skip {
            M += \$4;
            M2 += \$4 * \$4;
            count += 1;
        }
        END {
            avgM = M / count;
            avgM2 = M2 / count;
            X = (avgM2 - avgM * avgM) / \$1;
            print \$1, X
        }
    " {} \
    | tee $output_dir/suscept \
    | awk '
        { X[$1] += $2; count[$1] += 1 }
        END { for (t in count) print t, X[t] / count[t] }
    ' \
    | sort -n -k 1,1 \
    > $output_dir/suscept_avg
