#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
    echo "You need to pass arguments"
    exit 0
fi

path=$1
dirname=`basename $path`

mkdir -p data/processed/$dirname

find $path -type f \
    | xargs -I{} tail -n 1 {} \
    | tee data/processed/$dirname/temps \
    | awk '
        { E[$1] += $3; M[$1] += $4; count[$1] += 1 }
        END { for (t in E) print t, E[t]/count[t], M[t]/count[t] }
    ' \
    | sort -n -k 1,1 \
    > data/processed/$dirname/temps_avg
