[tool.poetry]
name = "ising-random-graphs"
version = "0.1.0"
description = ""
authors = ["Dawid Karp <dadulerk@gmail.com>"]
readme = "README.md"
packages = [{include = "ising"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
