#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "You need to pass arguments"
    exit 0
fi

graph=$1
steps=$2

now=`date +%s`
temps=`seq 150.0 10.0 350.0`
repeats=`seq 1 20`

echo "[*] compiling..."
compile

echo "[*] generating data..."
parallel -j4 --lb --delay 0.1 --progress \
    --results data/raw/ising_${steps}_{1/.}_${now}/{2}/{3} \
    ising {1} $steps {2} \
    ::: $graph \
    ::: $temps \
    ::: $repeats

echo "[*] cleaning up..."
datadir=`find . -name "*$now" -type d`
find $datadir -type f | grep -E ".seq|.err" | xargs -I{} rm {}
